FLUME-1020. Implement Kerberos security for HDFS Sink.
(Mike Percy via Arvind Prabhakar)


git-svn-id: https://svn.apache.org/repos/asf/incubator/flume/trunk@1303685 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/flume-ng b/bin/flume-ng
--- a/bin/flume-ng
+++ b/bin/flume-ng
@@ -19,44 +19,83 @@
 # under the License.
 #
 
-JAVA_OPTS="-Xmx20m"
-FLUME_CLASSPATH=""
-
-if [ -n "${FLUME_CONF_DIR}" -a -f "${FLUME_CONF_DIR}/flume-env.sh" ]; then
-    source "$FLUME_CONF_DIR/flume-env.sh"
-fi
+################################
+# constants
+################################
 
 FLUME_NODE_CLASS="org.apache.flume.node.Application"
 FLUME_AVRO_CLIENT_CLASS="org.apache.flume.client.avro.AvroCLIClient"
 
-if [ -z "${JAVA_HOME}" ] ; then
-    echo "Warning: JAVA_HOME not set!"
-    JAVA_DEFAULT=`type -p java`
-    [ -n "$JAVA_DEFAULT" ] || error "Unable to find java executable. Is it in your PATH?" 1
-    JAVA_BIN=`dirname $JAVA_DEFAULT`
-    JAVA_HOME=`dirname $JAVA_BIN`
-fi
+################################
+# functions
+################################
+
+info() {
+  local msg=$1
+
+  echo "Info: $msg" >&2
+}
 
 warn() {
   local msg=$1
 
-  echo "Warning: $msg"
+  echo "Warning: $msg" >&2
 }
 
 error() {
   local msg=$1
   local exit_code=$2
 
-  echo "Error: $msg"
+  echo "Error: $msg" >&2
 
   if [ -n "$exit_code" ] ; then
     exit $exit_code
   fi
 }
 
+# If avail, add Hadoop paths to the FLUME_CLASSPATH and to the
+# FLUME_JAVA_LIBRARY_PATH env vars.
+# Requires Flume jars to already be on FLUME_CLASSPATH.
+add_hadoop_paths() {
+  local HADOOP_IN_PATH=$(PATH="${HADOOP_HOME:-${HADOOP_PREFIX}}/bin:$PATH" \
+      which hadoop 2>/dev/null)
+
+  if [ -f "${HADOOP_IN_PATH}" ]; then
+    info "Including Hadoop libraries found via ($HADOOP_IN_PATH) for HDFS access"
+
+    # determine hadoop java.library.path and use that for flume
+    local HADOOP_CLASSPATH=""
+    local HADOOP_JAVA_LIBRARY_PATH=$(HADOOP_CLASSPATH="$FLUME_CLASSPATH" \
+        ${HADOOP_IN_PATH} org.apache.flume.tools.GetJavaProperty \
+        java.library.path 2>/dev/null)
+    if [ -n "${HADOOP_JAVA_LIBRARY_PATH}" ]; then
+      FLUME_JAVA_LIBRARY_PATH="$FLUME_JAVA_LIBRARY_PATH:$HADOOP_JAVA_LIBRARY_PATH"
+    fi
+
+    # determine hadoop classpath
+    HADOOP_CLASSPATH=$($HADOOP_IN_PATH classpath 2>/dev/null)
+
+    # hack up and filter hadoop classpath
+    local ELEMENTS=$(sed -e 's/:/ /g' <<<${HADOOP_CLASSPATH})
+    local ELEMENT
+    for ELEMENT in $ELEMENTS; do
+      local PIECE
+      for PIECE in $(echo $ELEMENT); do
+        if [[ $PIECE =~ slf4j-(api|log4j12).*\.jar ]]; then
+          info "Excluding $PIECE from classpath"
+          continue
+        else
+          FLUME_CLASSPATH="$FLUME_CLASSPATH:$PIECE"
+        fi
+      done
+    done
+
+  fi
+}
+
 display_help() {
   cat <<EOF
-usage: $0 [COMMAND] [OPTION]...
+Usage: $0 <command> [options]...
 
 commands:
   help                  display this help text
@@ -65,7 +104,7 @@ commands:
 
 global options:
   --conf,-c <conf>      use configs in <conf> directory
-  --classpath,-C <cp>   override the classpath completely
+  --classpath,-C <cp>   override the classpath for flume jars
 
 node options:
   --conf-file,-f        specify a config file (required)
@@ -84,57 +123,30 @@ in the classpath.
 EOF
 }
 
-run_node() {
-  local final_cp
+run_flume() {
   local FLUME_APPLICATION_CLASS
 
-  if [ -n "$opt_conf" ] ; then
-    final_cp="$opt_conf:"
-  fi
-
-  # If the user hasn't overridden the classpath, build it from the lib
-  # directory.
-  if [ -z "${FLUME_CLASSPATH}" ] ; then
-    FLUME_CLASSPATH="${FLUME_HOME}/lib/*"
+  if [ "$#" -gt 0 ]; then
+    FLUME_APPLICATION_CLASS=$1
+    shift
   else
-    warn "FLUME_CLASSPATH set to ${FLUME_CLASSPATH} - Hope you know what you're doing."
+    error "Must specify flume application class" 1
   fi
 
-  final_cp="${final_cp}${FLUME_CLASSPATH}"
-
-  [ -n "$opt_conf" ] || warn "No configuration directory set! Use --conf <dir> to override." 1
-
-  FLUME_APPLICATION_CLASS=$FLUME_NODE_CLASS
-
-  exec $JAVA_HOME/bin/java $JAVA_OPTS -cp "$final_cp" "$FLUME_APPLICATION_CLASS" $*
+  set -x
+  exec $JAVA_HOME/bin/java $JAVA_OPTS -cp "$FLUME_CLASSPATH" \
+      -Djava.library.path=$FLUME_JAVA_LIBRARY_PATH "$FLUME_APPLICATION_CLASS" $*
 }
 
-run_avro_client() {
-  local final_cp
-  local FLUME_APPLICATION_CLASS
+################################
+# main
+################################
 
-  if [ -n "$opt_conf" ] ; then
-    final_cp="$opt_conf:"
-  fi
+# set default params
+FLUME_CLASSPATH=""
+FLUME_JAVA_LIBRARY_PATH=""
+JAVA_OPTS="-Xmx20m"
 
-  # If the user hasn't overridden the classpath, build it from the lib
-  # directory.
-  if [ -z "${FLUME_CLASSPATH}" ] ; then
-    FLUME_CLASSPATH="${FLUME_HOME}/lib/*"
-  else
-    warn "FLUME_CLASSPATH set to ${FLUME_CLASSPATH} - Hope you know what you're doing."
-  fi
-
-  final_cp="${final_cp}${FLUME_CLASSPATH}"
-
-  [ -n "$opt_conf" ] || warn "No configuration directory set! Use --conf <dir> to override." 1
-
-  FLUME_APPLICATION_CLASS=$FLUME_AVRO_CLIENT_CLASS
-
-  exec $JAVA_HOME/bin/java $JAVA_OPTS -cp "$final_cp" "$FLUME_APPLICATION_CLASS" $*
-}
-
-opt_help=""
 opt_conf=""
 
 mode=$1
@@ -142,7 +154,8 @@ shift
 
 case "$mode" in
   help)
-    opt_help=1
+    display_help
+    exit 0
     ;;
   node)
     opt_node=1
@@ -152,7 +165,9 @@ case "$mode" in
     ;;
   *)
     error "Unknown or unspecified command '$mode'"
-    opt_help=1
+    echo
+    display_help
+    exit 1
     ;;
 esac
 
@@ -177,16 +192,62 @@ while [ -n "$*" ] ; do
   esac
 done
 
+# make opt_conf absolute
+if [[ -n "$opt_conf" && -d "$opt_conf" ]]; then
+  opt_conf=$(cd $opt_conf; pwd)
+fi
+
+# allow users to override the default env vars via conf/flume-env.sh
+if [ -z "$opt_conf" ]; then
+  warn "No configuration directory set! Use --conf <dir> to override."
+elif [ -f "$opt_conf/flume-env.sh" ]; then
+  source "$opt_conf/flume-env.sh"
+fi
+
+# find java
+if [ -z "${JAVA_HOME}" ] ; then
+  echo "Warning: JAVA_HOME not set!"
+  # Try to use Bigtop to autodetect JAVA_HOME if it's available
+  if [ -e /usr/libexec/bigtop-detect-javahome ]; then
+    . /usr/libexec/bigtop-detect-javahome
+  elif [ -e /usr/lib/bigtop-utils/bigtop-detect-javahome ]; then
+    . /usr/lib/bigtop-utils/bigtop-detect-javahome
+  else
+    JAVA_DEFAULT=`type -p java`
+    [ -n "$JAVA_DEFAULT" ] || error "Unable to find java executable. Is it in your PATH?" 1
+    JAVA_HOME=$(dirname $(dirname $JAVA_DEFAULT))
+  fi
+fi
+
+[ -n "${JAVA_HOME}" ] || error "Unable to find a suitable JAVA_HOME" 1
+
+# figure out where the flume distribution is
 if [ -z "${FLUME_HOME}" ] ; then
-  FLUME_HOME=`dirname $0`
-  FLUME_HOME="${FLUME_HOME}/../"
+  FLUME_HOME=$(cd $(dirname $(dirname $0)); pwd)
 fi
 
-if [ -n "$opt_help" ] ; then
-  display_help
-elif [ -n "$opt_node" ] ; then
-  run_node $args
+# If the user hasn't overridden the classpath, build it from the dist lib dir
+if [ -z "${FLUME_CLASSPATH}" ] ; then
+  FLUME_CLASSPATH="${FLUME_HOME}/lib/*"
+else
+  warn "Base FLUME_CLASSPATH set to ($FLUME_CLASSPATH) - Hope you know what you're doing."
+fi
+
+# look for hadoop libs
+add_hadoop_paths
+
+# prepend conf dir to classpath
+if [ -n "$opt_conf" ]; then
+  FLUME_CLASSPATH="$opt_conf:$FLUME_CLASSPATH"
+fi
+
+# finally, invoke the appropriate command
+if [ -n "$opt_node" ] ; then
+  run_flume $FLUME_NODE_CLASS $args
 elif [ -n "$opt_avro_client" ] ; then
-  run_avro_client $args
+  run_flume $FLUME_AVRO_CLIENT_CLASS $args
+else
+  error "This message should never appear" 1
 fi
 
+exit 0
