FLUME-418: Add batching and compression arguments to agent and collectors - compression and batching before retry logic and buffering in sinks - add test to make sure compressed version works
From: Jonathan Hsieh <jon@cloudera.com>

git-svn-id: https://svn.apache.org/repos/asf/incubator/flume/trunk@1155917 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/test-endtoend/test-simple-be b/test-endtoend/test-simple-be
--- a/test-endtoend/test-simple-be
+++ b/test-endtoend/test-simple-be
@@ -1,4 +1,4 @@
-#!/usr/bin/env /bin/bash
+#!/usr/bin/env /bin/sh
 # Licensed to Cloudera, Inc. under one
 # or more contributor license agreements.  See the NOTICE file
 # distributed with this work for additional information
@@ -21,14 +21,16 @@
 # specific number of events were delivered.  It expects that a node
 # and master are running on the localhost
 
-DIR=`dirname $0`
-FLUME="$DIR/../bin/flume"
+DIR=`dirname $0`/..
+FLUME_HOME=${FLUME_HOME:-$DIR/flume-distribution/target/flume-*/flume*}
+FLUME=${FLUME_HOME}/bin/flume
+
 MASTER=localhost
 NODE1=`hostname`
 NODE2=`hostname`
-TMPDIR=/tmp/test-be
+FLUMELOGDIR=/tmp/test-be-`date +%Y%m%d-%H%M%S.%N`
 
-rm -rf $TMPDIR || { echo "Unable to delete $TMPDIR" ; exit 1 ; }
+rm -rf $FLUMELOGDIR || { echo "Unable to delete $FLUMELOGDIR" ; exit 1 ; }
 
 $FLUME shell <<EOF
 connect $MASTER
@@ -44,7 +46,7 @@ exec spawn $NODE2 node
 exec noop 10000
 
 ## Setup an agent collector topology using autoBEChains.
-exec config collector  autoCollectorSource 'collectorSink("file://$TMPDIR","data")'
+exec config collector  autoCollectorSource 'collectorSink("file://$FLUMELOGDIR","data",5000)'
 exec config node 'asciisynth(500)' '{delay(200)=>autoBEChain}'
 
 ## Wait for the node to become active, and then done.
@@ -56,7 +58,9 @@ exec decommission node
 exec decommission collector
 
 # waitForNodesDecommissioned
-wait 5000
+# waitForNodesDone 20000 collector ## this doesn't work anymore.
+exec noop 5000
+exec noop 5000
 
 quit
 EOF
@@ -68,7 +72,7 @@ fi
 
 sleep 5s
 
-COUNT=`wc -l $TMPDIR/* | tail -1 | awk '{print $1}'`
+COUNT=`wc -l $FLUMELOGDIR/* | tail -1 | awk '{print $1}'`
 echo count messages $COUNT
 if [ "$COUNT" != 500 ] ; then
     echo "FAIL"
@@ -76,4 +80,4 @@ if [ "$COUNT" != 500 ] ; then
 fi
 
 echo "SUCCESS"
-rm -rf $TMPDIR || { echo "test succeeded but failed to rm $TMPDIR" ; exit 1; } 
+rm -rf $FLUMELOGDIR || { echo "test succeeded but failed to rm $FLUMELOGDIR" ; exit 1; } 
diff --git a/test-endtoend/test-simple-be-batch b/test-endtoend/test-simple-be-batch
--- a/test-endtoend/test-simple-be-batch
+++ b/test-endtoend/test-simple-be-batch
@@ -15,8 +15,9 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+
 ####
-# This test runs an agent in end-to-end mode and verifies that a
+# This test runs an agent in best effort mode and verifies that a
 # specific number of events were delivered.  It expects that a node
 # and master are running on the localhost
 
@@ -27,11 +28,9 @@ FLUME=${FLUME_HOME}/bin/flume
 MASTER=localhost
 NODE1=`hostname`
 NODE2=`hostname`
-FLUMELOGDIR=/tmp/test-e2e-`date +%Y%m%d-%H%M%S.%N`
+FLUMELOGDIR=/tmp/test-be-batch-`date +%Y%m%d-%H%M%S.%N`
 
-# remove stale write-ahead or failover logs
-rm -rf /tmp/flume/agent  || { echo "Unable to delete $FLUMELOGDIR" ; exit 1 ; }
-rm -rf $FLUMELOGDIR  || { echo "Unable to delete $FLUMELOGDIR" ; exit 1 ; }
+rm -rf $FLUMELOGDIR || { echo "Unable to delete $FLUMELOGDIR" ; exit 1 ; }
 
 $FLUME shell <<EOF
 connect $MASTER
@@ -46,17 +45,13 @@ exec spawn $NODE2 node
 # enough for two heartbeats, to get ips to master
 exec noop 10000
 
-
 ## Setup an agent collector topology using autoBEChains.
 exec config collector  autoCollectorSource 'collectorSink("file://$FLUMELOGDIR","data",5000)'
-exec config node 'asciisynth(500)' '{delay(200)=>autoE2EChain}'
+exec config node 'asciisynth(500)' 'delay(200) agentBESink("$NODE1",batchCount=10)'
 
 ## Wait for the node to become active, and then done.
 waitForNodesActive 10000 node
 waitForNodesDone 200000 node
-
-# Wait for WAL to flush
-exec noop 60000
 
 ## Yea! done.
 exec decommission node
@@ -69,6 +64,7 @@ exec noop 5000
 quit
 EOF
 
+
 if [ "$?" -ne 0 ] ; then 
   echo "flume shell script failed"; exit 1; 
 fi
@@ -79,10 +75,8 @@ COUNT=`wc -l $FLUMELOGDIR/* | tail -1 | awk '{print $1}'`
 echo count messages $COUNT
 if [ "$COUNT" != 500 ] ; then
     echo "FAIL"
-    exit -1
+    exit 1
 fi
 
 echo "SUCCESS"
-rm -rf $FLUMELOGDIR
-
-
+rm -rf $FLUMELOGDIR || { echo "test succeeded but failed to rm $FLUMELOGDIR" ; exit 1; } 
diff --git a/test-endtoend/test-simple-dfo b/test-endtoend/test-simple-dfo
--- a/test-endtoend/test-simple-dfo
+++ b/test-endtoend/test-simple-dfo
@@ -1,4 +1,4 @@
-#!/usr/bin/env /bin/bash
+#!/usr/bin/env /bin/sh
 # Licensed to Cloudera, Inc. under one
 # or more contributor license agreements.  See the NOTICE file
 # distributed with this work for additional information
@@ -20,17 +20,18 @@
 # specific number of events were delivered.  It expects that a node
 # and master are running on the localhost
 
+DIR=`dirname $0`/..
+FLUME_HOME=${FLUME_HOME:-$DIR/flume-distribution/target/flume-*/flume*}
+FLUME=${FLUME_HOME}/bin/flume
 
-DIR=`dirname $0`
-FLUME="$DIR/../bin/flume"
 MASTER=localhost
 NODE1=`hostname`
 NODE2=`hostname`
-TMPDIR=/tmp/test-dfo
+FLUMELOGDIR=/tmp/test-dfo-`date +%Y%m%d-%H%M%S.%N`
 
 # remove stale write-ahead or failover logs
-rm -rf /tmp/flume/agent  || { echo "Unable to delete $TMPDIR" ; exit 1 ; }
-rm -rf $TMPDIR || { echo "Unable to delete $TMPDIR" ; exit 1 ; }
+rm -rf /tmp/flume/agent  || { echo "Unable to delete $FLUMELOGDIR" ; exit 1 ; }
+rm -rf $FLUMELOGDIR || { echo "Unable to delete $FLUMELOGDIR" ; exit 1 ; }
 
 $FLUME shell <<EOF
 connect $MASTER
@@ -47,7 +48,7 @@ exec noop 10000
 
 
 ## Setup an agent collector topology using autoBEChains.
-exec config collector  autoCollectorSource 'collectorSink("file://$TMPDIR","data")'
+exec config collector  autoCollectorSource 'collectorSink("file://$FLUMELOGDIR","data",5000)'
 exec config node 'asciisynth(500)' '{delay(200)=>autoDFOChain}'
 
 ## Wait for the node to become active, and then done.
@@ -59,7 +60,8 @@ exec decommission node
 exec decommission collector
 
 # waitForNodesDecommissioned
-wait 5000
+exec noop 5000
+exec noop 5000
 
 quit
 EOF
@@ -70,7 +72,7 @@ fi
 
 sleep 5s
 
-COUNT=`wc -l $TMPDIR/* | tail -1 | awk '{print $1}'`
+COUNT=`wc -l $FLUMELOGDIR/* | tail -1 | awk '{print $1}'`
 echo count messages $COUNT
 if [ "$COUNT" != 500 ] ; then
     echo "FAIL"
@@ -78,4 +80,4 @@ if [ "$COUNT" != 500 ] ; then
 fi
 
 echo "SUCCESS"
-rm -rf $TMPDIR || { echo "test succeeded but failed to rm $TMPDIR" ; exit 1; } 
+rm -rf $FLUMELOGDIR || { echo "test succeeded but failed to rm $FLUMELOGDIR" ; exit 1; } 
